### ISSUE TITLE
ImageOptim for photos and versions specific to pixel density

### ISSUE THREAD

**Issue by pkd2512** [reuters-graphics/graphics-kit-publisher#36]
### WHY
Photos and ai2html images can get pretty heavy, running into megabytes. Lossy compression using Photoshop or Illustrator is not good enough. Cannot reduce dimensions either because we need them to be crisp for retina screens as well, so need to preserve at least 72ppi (default for screens) at `1x` dimensions. 

### WHAT
I have been using [ImageOptim](https://imageoptim.com/mac), which is the best I have seen for smart lossy compression while preserving quality for pngs, jpegs and svgs. ImageOptim uses precise algorithms to avoid colour shifts, which can make it slow but totally worth the wait. It comes with an API for a lot of the work on the server like assets generation etc as well as a [CLI version](https://www.npmjs.com/package/imageoptim-cli) to optimise during build.

May also consider adding separate `@1x` and `@2x` versions of bitmap assets

**Comment by hobbes7878** [comment]
Added a sharp implementation in https://github.com/reuters-graphics/graphics-kit-publisher/pull/40, which landed in `0.2.0`.

Flags large images by file size.

Images can now be optimised in bulk or optimised and/or resized one at a time.

Can also opt out of the whole process at the top.

**Comment by hobbes7878** [comment]
Svelte has added their own [optimised image handling](https://kit.svelte.dev/docs/images#sveltejs-enhanced-img). Going to close this in favour of that at: https://github.com/reuters-graphics/bluprint_graphics-kit/issues/108
