### ISSUE TITLE
Consider splitting image processing into a separate CLI

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/graphics-kit-publisher#42]
The measureImages method is run at [the top of the upload command](https://github.com/reuters-graphics/graphics-kit-publisher/blob/master/src/upload/index.js#L18), but it's really off in a corner to itself.

We currently aren't using the manifest it creates anywhere in the upload process or [SEO component](https://github.com/reuters-graphics/graphics-svelte-components/blob/master/src/lib/SEO/index.svelte), so there's no real reason it _has_ to be in this package.

Splitting it out would mean we could add some additional methods for doing things like converting JPEGs/PNGs to webp images or making multiple size images to go with srcsets. Both those could be better paired with an intelligent component that _does_ use the manifest to use srcsets where available and creates image fallbacks for the webp images.

cc'ing @pkd2512 who'll likely be interested in the idea. :)

**Comment by pkd2512** [comment]
This sounds like a good idea. Happy to chat further. I was reading the MDN docs on the same. Sharing for reference https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by hobbes7878** [comment]
Just idly looking into possibilities here, a couple things:

[`vite-imagetools`](https://github.com/JonasKruckenberg/imagetools/tree/main/packages/vite) is the closest pluggable option in SvelteKit world. It does appear to work, but srcset generation with `<picture>` tags [isn't great](https://github.com/JonasKruckenberg/imagetools/issues/260), and it means needing to import the images _in code_ (rules out image paths coming from gdocs without dynamic importing), with not especially friendly [directives](https://github.com/JonasKruckenberg/imagetools/blob/main/docs/directives.md).

I think our immediate needs are more limited than what's in imagetools, but I'm also not super thrilled with building and maintaining our own bespoke thing.

BUT if we did...

I think the idea is a CLI we can point at the images directory, which walks the files and provides options to resize, optimise or both with advanced opts to create srcsets. That would spit out a manifest file that could be used in conjunction with a custom component to create images.

I also think we'd want to _preserve_ the original image, rather than overwrite it so the operation is safe. If we could rely on strict naming/folder-ing conventions, then I think someone could provide the path to the _original image_ and we could use it to produce, e.g., a srcset image from the manifest. Perhaps we create a reserved directory that's like `images/optimised` so there's a an easy division between raw and optimised/resized files.

May want to later exclude the raw images from the uploaded package, but maybe that's less important to figure out right now and allows some flexibility to fall back to raw images if you want.

The prompts in the CLI seem like they would be a bit fiddly. Maybe users can describe _an operation_ and then select multiple images to perform it on?

CLI would also need to keep track of whether a source image file _has changed_ and know to delete previous optimised copies and re-prompt. Can use the width/height/size metadata we want to include in the manifest to determine an image that no longer matches, maybe.

Lastly, also during testing, noticed the graphics server does not currently allow `.webp` images according to [the docs](https://thehub.thomsonreuters.com/docs/DOC-2966287). Should request this filetype be added, but converting to modern formats is a dead end for us until that's added...

**Comment by hobbes7878** [comment]
Svelte has added their own [optomised image handling](https://kit.svelte.dev/docs/images#sveltejs-enhanced-img). Going to close this in favour of that at: https://github.com/reuters-graphics/bluprint_graphics-kit/issues/108
